import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalsProvider, ToasterProvider } from "@/providers";
import ClientOnly from "@/components/layout/ClientOnly";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Uscategui Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider/>
          {/* <ModalsProvider/> */}
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
